apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - image: iffakhry/alta-be7
          name: go-app
          ports:
            - containerPort: 8080